name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.2'
          extension-csv: mbstring, bcmath
      - name: Composer install
        run: composer global require "laravel/envoy=~2.8"
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          #config: ${{ secrets.CONFIG }} # ssh_config; optional
          if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)
          run: ssh-keygen -R api.rediscoverapp.tech
      - name: Deploy with Envoy
        run: envoy run deploy --server=main
